const books = {
    Genesis: require('../chunks/Genesis.js'),
    Exodus: require('../chunks/Exodus.js'),
    Leviticus: require('../chunks/Leviticus.js'),
    Numbers: require('../chunks/Numbers.js'),
    Deuteronomy: require('../chunks/Deuteronomy.js'),
    Joshua: require('../chunks/Joshua.js'),
    Judges: require('../chunks/Judges.js'),
    Ruth: require('../chunks/Ruth.js'),
    '1Samuel': require('../chunks/1Samuel.js'),
    '2Samuel': require('../chunks/2Samuel.js'),
    '1Kings': require('../chunks/1Kings.js'),
    '2Kings': require('../chunks/2Kings.js'),
    '1Chronicles': require('../chunks/1Chronicles.js'),
    '2Chronicles': require('../chunks/2Chronicles.js'),
    Ezra: require('../chunks/Ezra.js'),
    Nehemiah: require('../chunks/Nehemiah.js'),
    Esther: require('../chunks/Esther.js'),
    Job: require('../chunks/Job.js'),
    Psalms: require('../chunks/Psalms.js'),
    Proverbs: require('../chunks/Proverbs.js'),
    Ecclesiastes: require('../chunks/Ecclesiastes.js'),
    'Song of Solomon': require('../chunks/Song of Solomon.js'),
    Isaiah: require('../chunks/Isaiah.js'),
    Jeremiah: require('../chunks/Jeremiah.js'),
    Lamentations: require('../chunks/Lamentations.js'),
    Ezekiel: require('../chunks/Ezekiel.js'),
    Daniel: require('../chunks/Daniel.js'),
    Hosea: require('../chunks/Hosea.js'),
    Joel: require('../chunks/Joel.js'),
    Amos: require('../chunks/Amos.js'),
    Obadiah: require('../chunks/Obadiah.js'),
    Jonah: require('../chunks/Jonah.js'),
    Micah: require('../chunks/Micah.js'),
    Nahum: require('../chunks/Nahum.js'),
    Habakkuk: require('../chunks/Habakkuk.js'),
    Zephaniah: require('../chunks/Zephaniah.js'),
    Haggai: require('../chunks/Haggai.js'),
    Zechariah: require('../chunks/Zechariah.js'),
    Malachi: require('../chunks/Malachi.js'),

    Matthew: require('../chunks/Matthew.js'),
    Mark: require('../chunks/Mark.js'),
    Luke: require('../chunks/Luke.js'),
    John: require('../chunks/John.js'),
    Acts: require('../chunks/Acts.js'),
    Romans: require('../chunks/Romans.js'),
    '1Corinthians': require('../chunks/1Corinthians.js'),
    '2Corinthians': require('../chunks/2Corinthians.js'),
    Galatians: require('../chunks/Galatians.js'),
    Ephesians: require('../chunks/Ephesians.js'),
    Philippians: require('../chunks/Philippians.js'),
    Colossians: require('../chunks/Colossians.js'),
    '1Thessalonians': require('../chunks/1Thessalonians.js'),
    '2Thessalonians': require('../chunks/2Thessalonians.js'),
    '1Timothy': require('../chunks/1Timothy.js'),
    '2Timothy': require('../chunks/2Timothy.js'),
    Titus: require('../chunks/Titus.js'),
    Philemon: require('../chunks/Philemon.js'),
    Hebrews: require('../chunks/Hebrews.js'),
    James: require('../chunks/James.js'),
    '1Peter': require('../chunks/1Peter.js'),
    '2Peter': require('../chunks/2Peter.js'),
    '1John': require('../chunks/1John.js'),
    '2John': require('../chunks/2John.js'),
    '3 John': require('../chunks/3John.js'),
    Jude: require('../chunks/Jude.js'),
    Revelation: require('../chunks/Revelation.js')
}

module.exports = books
    
