const books = {
    Genesis: require('../chunks/Genesis.js'),
    Exodus: require('../chunks/Exodus.js'),
    Leviticus: require('../chunks/Leviticus.js'),
    Numbers: require('../chunks/Numbers.js'),
    Deuteronomy: require('../chunks/Deuteronomy.js'),
    Joshua: require('../chunks/Joshua.js'),
    Judges: require('../chunks/Judges.js'),
    Ruth: require('../chunks/Ruth.js'),
    '1 Samuel': require('../chunks/1 Samuel.js'),
    '2 Samuel': require('../chunks/2 Samuel.js'),
    '1 Kings': require('../chunks/1 Kings.js'),
    '2 Kings': require('../chunks/2 Kings.js'),
    '1 Chronicles': require('../chunks/1 Chronicles.js'),
    '2 Chronicles': require('../chunks/2 Chronicles.js'),
    Ezra: require('../chunks/Ezra.js'),
    Nehemiah: require('../chunks/Nehemiah.js'),
    Esther: require('../chunks/Esther.js'),
    Job: require('../chunks/Job.js'),
    Psalms: require('../chunks/Psalms.js'),
    Proverbs: require('../chunks/Proverbs.js'),
    Ecclesiastes: require('../chunks/Ecclesiastes.js'),
    'Song of Solomon': require('../chunks/Song of Solomon.js'),
    Isaiah: require('../chunks/Isaiah.js'),
    Jeremiah: require('../chunks/Jeremiah.js'),
    Lamentations: require('../chunks/Lamentations.js'),
    Ezekiel: require('../chunks/Ezekiel.js'),
    Daniel: require('../chunks/Daniel.js'),
    Hosea: require('../chunks/Hosea.js'),
    Joel: require('../chunks/Joel.js'),
    Amos: require('../chunks/Amos.js'),
    Obadiah: require('../chunks/Obadiah.js'),
    Jonah: require('../chunks/Jonah.js'),
    Micah: require('../chunks/Micah.js'),
    Nahum: require('../chunks/Nahum.js'),
    Habakkuk: require('../chunks/Habakkuk.js'),
    Zephaniah: require('../chunks/Zephaniah.js'),
    Haggai: require('../chunks/Haggai.js'),
    Zechariah: require('../chunks/Zechariah.js'),
    Malachi: require('../chunks/Malachi.js'),

    Matthew: require('../chunks/Matthew.js'),
    Mark: require('../chunks/Mark.js'),
    Luke: require('../chunks/Luke.js'),
    John: require('../chunks/John.js'),
    Acts: require('../chunks/Acts.js'),
    Romans: require('../chunks/Romans.js'),
    '1 Corinthians': require('../chunks/1 Corinthians.js'),
    '2 Corinthians': require('../chunks/2 Corinthians.js'),
    Galatians: require('../chunks/Galatians.js'),
    Ephesians: require('../chunks/Ephesians.js'),
    Philippians: require('../chunks/Philippians.js'),
    Colossians: require('../chunks/Colossians.js'),
    '1 Thessalonians': require('../chunks/1 Thessalonians.js'),
    '2 Thessalonians': require('../chunks/2 Thessalonians.js'),
    '1 Timothy': require('../chunks/1 Timothy.js'),
    '2 Timothy': require('../chunks/2 Timothy.js'),
    Titus: require('../chunks/Titus.js'),
    Philemon: require('../chunks/Philemon.js'),
    Hebrews: require('../chunks/Hebrews.js'),
    James: require('../chunks/James.js'),
    '1 Peter': require('../chunks/1 Peter.js'),
    '2 Peter': require('../chunks/2 Peter.js'),
    '1 John': require('../chunks/1 John.js'),
    '2 John': require('../chunks/2 John.js'),
    '3 John': require('../chunks/3 John.js'),
    Jude: require('../chunks/Jude.js'),
    Revelation: require('../chunks/Revelation.js')
}

module.exports = books
    
